name: option_battles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
  fl_chart: ^0.40.0
  web_socket_channel: ^2.2.4
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
