name: option_battles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^2.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img.png
    - lib/assets/lightening.png
    - lib/assets/badger.png
    - lib/assets/1911.mp3
    - lib/assets/1911.gif
    - .env
