name: option_battles
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  web_socket_channel: ^2.2.4
  provider: ^6.1.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img.png
    - lib/assets/badger.png
    - .env
